### ISSUE TITLE
[IFE02-1] Fix and Remove White Space right side of Signup and Signin Page	

### ISSUE THREAD

**Issue by dinogomez** [dinogomez/htdocs#16]
- Fix and Remove White Space right side of Signup and Sign-in Page	
![image](https://user-images.githubusercontent.com/41871666/153216786-7678e67c-5485-49c2-bdf2-3c0f69316297.png)
![image](https://user-images.githubusercontent.com/41871666/153216839-3b481cc4-3eec-4780-a773-41d5983782d7.png)

- Reduce and Balance Height of Signup Page	
![image](https://user-images.githubusercontent.com/41871666/153216922-4a6897db-b215-429d-a1d0-7f8fa450e742.png)

**Comment by Ablaze0313** [comment]
For references:

![1](https://user-images.githubusercontent.com/61894984/154835038-f9d22f1c-f794-4fac-8334-9fa4678b0196.png)
![2](https://user-images.githubusercontent.com/61894984/154835052-306fc22a-c59b-450f-b849-28f57b5f9348.png)
